### PR TITLE
Fixed Unicode support for defaults/main.yml.

### PR DESCRIPTION
**Pull request by ypid**
* http://stackoverflow.com/a/14919377/2239985
* Solution might not be the best but it works and switching to Python 3
  would solve this anyway so I propose this hack.

### CODE REVIEW

**Comment by nickjj** [comment]
What happens if you just put ``#-*- coding: utf-8 -*-`` as the very first line in the file, instead of `sys.setdefaultencoding('utf-8')`?

**Comment by ypid** [comment]
This does not solve the problem … It changes nothing. Unicode should be the default …

**Comment by ypid** [comment]
Any news? I have been using this branch from the time I open this PR without issues …

**Comment by nickjj** [comment]
Thanks for the contribution, sorry about the long delay on this.

**Comment by ypid** [comment]
Thanks @nickjj :+1:

**Comment by nickjj** [comment]
@ypid, your recent PRs are in `v0.5.5`.

**Pull request merged**
