### PR TITLE
Fix code execution vulnerability by switching to yaml.safe_load

### PR DESCRIPTION
**Pull request by ypid**
Ref: https://github.com/yaml/pyyaml/issues/5

You might want to make a release with that :wink:

### CODE REVIEW

**Comment by ypid** [comment]
Note that the failing CI tests are unrelated to this PR.

**Comment by nickjj** [comment]
Hi,

Thanks for reporting this.

Would you mind addressing those flake8 issues in a different PR? Then I'll merge them both in and release a new version.

**Comment by ypid** [comment]
Thanks. Here you go: #56

**Comment by nickjj** [comment]
Thanks again.

**Pull request merged**
